package io.github.marioponceg.keystone.data.realm

import io.github.marioponceg.keystone.domain.model.Realm
import io.github.marioponceg.keystone.domain.model.Region
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class BundledRealmRepositoryTest {

    private val repository = BundledRealmRepository()

    @Test
    fun `eu realms include Tarren Mill with its slug`() {
        val eu = repository.realms(Region.EU)
        assertContains(eu, Realm("Tarren Mill", "tarren-mill"))
    }

    @Test
    fun `every region loads a non-empty list`() {
        Region.entries.forEach { region ->
            assertTrue(repository.realms(region).isNotEmpty(), "empty realms for $region")
        }
    }

    @Test
    fun `realms are sorted alphabetically by name`() {
        val names = repository.realms(Region.EU).map { it.name }
        assertEquals(names.sortedWith(String.CASE_INSENSITIVE_ORDER), names)
    }

    @Test
    fun `a missing snapshot fails loudly rather than yielding an empty picker`() {
        val repository = BundledRealmRepository(openResource = { null })
        val failure = assertFailsWith<IllegalStateException> { repository.realms(Region.EU) }
        assertContains(failure.message.orEmpty(), "/realms/eu.json")
    }

    @Test
    fun `a corrupt snapshot degrades to an empty list`() {
        val repository = BundledRealmRepository(openResource = { "not json at all".byteInputStream() })
        assertEquals(emptyList(), repository.realms(Region.EU))
    }

    // The bundled JSON is regenerated by scripts/generate-realms.py; these guard against a bad
    // regeneration landing silently, since the whole "a realm cannot be mistyped" guarantee
    // rests on this data.

    @Test
    fun `every region's realms have unique slugs and no blank fields`() {
        Region.entries.forEach { region ->
            val realms = repository.realms(region)
            val slugs = realms.map { it.slug }
            assertEquals(slugs.size, slugs.distinct().size, "duplicate slugs in $region")
            assertTrue(
                realms.all { it.name.isNotBlank() && it.slug.isNotBlank() },
                "blank name or slug in $region",
            )
        }
    }

    @Test
    fun `slugs are lowercase and contain only letters, digits and hyphens`() {
        val slugPattern = Regex("[\\p{L}0-9-]+")
        val malformed = Region.entries
            .flatMap { repository.realms(it) }
            .map { it.slug }
            .filterNot { it.matches(slugPattern) && it == it.lowercase() }
        assertEquals(emptyList(), malformed, "malformed realm slugs")
    }
}
